import localFont from "next/font/local";
import "./globals.css";
import "../components/static/styles/css/shake.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Goldman } from 'next/font/google';


const GoldmanFont = Goldman({
    subsets: ['latin'],
    weight: ['400'],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { DrawerStateProvider } from '../context/DrawerContext';
import { CartProvider } from '../context/CartContext';
import CartSync from '../components/CartSync';
import { AuthProvider } from '../context/AuthContext';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${GoldmanFont.className} antialiased`}
      >
        <DrawerStateProvider>
          <AuthProvider>
            <CartProvider>
              <CartSync />
                <Header />
                  <main>{children}</main>
                <Footer />
            </CartProvider>
          </AuthProvider>
        </DrawerStateProvider>
      </body>
    </html>
  );
}